theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: false
  logo:
    header: /assets/images/logo-blanc.svg
    footer: /assets/images/logo.svg